version: '3'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    container_name: omni_seeker
    volumes:
      - .:/omni_seeker
    depends_on:
      - db
    entrypoint: /bin/bash
    stdin_open: true
    tty: true